-- ============================================================
-- VENUS - Schema base vide
-- ============================================================
-- Usage :
--   psql -d venus -f database/schema.sql
--
-- Ce script cree uniquement la structure necessaire a l'application.
-- Il n'insere aucune tuile, aucun favori, aucun mail et aucun tracking.
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.category (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.projects (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    subtext varchar(512) DEFAULT 'test',
    resources_details text,
    description_details text,
    contact_details text,
    comments text,
    hidden integer DEFAULT 0,
    display_order integer
);

CREATE TABLE IF NOT EXISTS public.project_category (
    project_id integer NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    category_id integer NOT NULL REFERENCES public.category(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, category_id)
);

CREATE INDEX IF NOT EXISTS idx_project_category_project_id
    ON public.project_category (project_id);

CREATE INDEX IF NOT EXISTS idx_project_category_category_id
    ON public.project_category (category_id);

CREATE TABLE IF NOT EXISTS public.users (
    uid varchar(100) PRIMARY KEY,
    username varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_favorite (
    uid varchar(100) NOT NULL REFERENCES public.users(uid) ON DELETE CASCADE,
    project_id integer NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    PRIMARY KEY (uid, project_id)
);

CREATE TABLE IF NOT EXISTS public.mails (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    objet text NOT NULL,
    date timestamp without time zone NOT NULL,
    sender text,
    content text,
    categorie_id integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.tile_click_tracking (
    tile_id integer NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    tab_1 boolean NOT NULL DEFAULT false,
    tab_2 boolean NOT NULL DEFAULT false,
    tab_3 boolean NOT NULL DEFAULT false,
    clicked_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tile_click_tracking_tile_id
    ON public.tile_click_tracking (tile_id);

CREATE INDEX IF NOT EXISTS idx_tile_click_tracking_clicked_at
    ON public.tile_click_tracking (clicked_at);

CREATE TABLE IF NOT EXISTS public.tile_stats_export_log (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filter_label varchar(160) NOT NULL DEFAULT 'toutes les dates',
    username varchar(120) NOT NULL DEFAULT 'admin',
    nom varchar(160) NOT NULL DEFAULT 'admin',
    date_from date NULL,
    date_to date NULL,
    exported_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tile_stats_export_log_exported_at
    ON public.tile_stats_export_log (exported_at DESC);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cipen') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
            public.category,
            public.projects,
            public.project_category,
            public.users,
            public.user_favorite,
            public.mails
        TO cipen;

        GRANT SELECT, INSERT ON TABLE
            public.tile_click_tracking,
            public.tile_stats_export_log
        TO cipen;

        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cipen;
    END IF;
END
$$;

COMMIT;
