-- Venus database schema
-- Empty schema only: no production/preproduction data.

BEGIN;

CREATE TABLE IF NOT EXISTS public.category (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom character varying(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.projects (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title character varying(255) NOT NULL,
    subtext character varying(512) DEFAULT 'test'::character varying,
    resources_details text,
    description_details text,
    contact_details text,
    comments text,
    hidden integer DEFAULT 0,
    display_order integer
);

CREATE TABLE IF NOT EXISTS public.project_category (
    project_id integer NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    category_id integer NOT NULL REFERENCES public.category(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, category_id)
);

CREATE TABLE IF NOT EXISTS public.mails (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    objet text NOT NULL,
    date timestamp without time zone NOT NULL,
    sender text,
    content text,
    categorie_id integer DEFAULT 1 NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users (
    uid character varying(100) PRIMARY KEY,
    username character varying(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_favorite (
    uid character varying(100) NOT NULL REFERENCES public.users(uid) ON DELETE CASCADE,
    project_id integer NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    PRIMARY KEY (uid, project_id)
);

CREATE TABLE IF NOT EXISTS public.tile_click_tracking (
    tile_id integer NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    tab_1 boolean NOT NULL DEFAULT false,
    tab_2 boolean NOT NULL DEFAULT false,
    tab_3 boolean NOT NULL DEFAULT false,
    clicked_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_project_category_category_id
    ON public.project_category USING btree (category_id);

CREATE INDEX IF NOT EXISTS idx_project_category_project_id
    ON public.project_category USING btree (project_id);

CREATE INDEX IF NOT EXISTS idx_tile_click_tracking_tile_id
    ON public.tile_click_tracking USING btree (tile_id);

CREATE INDEX IF NOT EXISTS idx_tile_click_tracking_clicked_at
    ON public.tile_click_tracking USING btree (clicked_at);

GRANT ALL ON TABLE public.category TO cipen;
GRANT ALL ON TABLE public.projects TO cipen;
GRANT ALL ON TABLE public.project_category TO cipen;
GRANT ALL ON TABLE public.mails TO cipen;
GRANT ALL ON TABLE public.users TO cipen;
GRANT ALL ON TABLE public.user_favorite TO cipen;
GRANT SELECT, INSERT ON TABLE public.tile_click_tracking TO cipen;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cipen;

COMMIT;
